workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        NODE_VERSION: 20
        XCODE_VERSION: 15.0

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Next.js app
        script: |
          npm install -g @capacitor/cli
          npm run build
          npx cap sync ios

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build

    artifacts:
      - ios/App/build/Build/Products/Release-iphoneos/*.app
      - ios/App/build/Build/Products/Release-iphoneos/*.ipa

    publishing:
      email:
        recipients:
          - your@email.com  # 👈 replace this with your actual email
