workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
      node: $NODE_VERSION
      xcode: 15.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js app
        script: |
          npm run build
          npx cap copy
      - name: Prepare iOS project
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -derivedDataPath build
    artifacts:
      - ios/App/build/**/*.ipa
    publishing:
      email:
        recipients:
          - cedricroberge10@gmail.com