workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    # Pull secrets/vars from the "ios" group (set these in Codemagic → Environment variables)
    #   APP_STORE_CONNECT_PRIVATE_KEY (base64 of .p8)
    #   APP_STORE_CONNECT_KEY_ID
    #   APP_STORE_CONNECT_ISSUER_ID
    #   CM_EMAIL
    #   NEXT_PUBLIC_SUPABASE_URL
    #   NEXT_PUBLIC_SUPABASE_ANON_KEY
    #   APPLE_TEAM_ID
    #   BUNDLE_ID
    environment:
      groups:
        - ios
      vars:
        NODE_VERSION: 20
        XCODE_VERSION: 15.0

    cache:
      cache_paths:
        - ~/.npm
        - $HOME/Library/Caches/CocoaPods
        - ios/**/Pods

    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm -v
          npm ci

      - name: Build Next.js app (static export) & sync Capacitor
        script: |
          npm install -g @capacitor/cli
          npm run build
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Set up automatic signing
        script: |
          export APP_STORE_CONNECT_KEY_IDENTIFIER="$APP_STORE_CONNECT_KEY_ID"
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles --project ios/App/App.xcodeproj

      - name: Build & sign IPA (App Store)
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-configuration Release \
            --export-method app-store \
            --archive-flags "DEVELOPMENT_TEAM=$APPLE_TEAM_ID PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID CODE_SIGN_STYLE=Manual"

    artifacts:
      - $CM_BUILD_DIR/ios_build/*.ipa
      - $CM_BUILD_DIR/**/*.ipa
      - $CM_BUILD_DIR/ios_archive.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

      email:
        recipients:
          - $CM_EMAIL
