workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        NODE_VERSION: 20
        XCODE_VERSION: 15.0

    # ---- INPUTS (bridge env vars -> YAML-safe references) ----
    inputs:
      APP_STORE_CONNECT_PRIVATE_KEY:
        description: Apple API key (.p8) Base64 (from env var)
        default: ${APP_STORE_CONNECT_PRIVATE_KEY}
      APP_STORE_CONNECT_KEY_ID:
        description: Apple Key ID (from env var)
        default: ${APP_STORE_CONNECT_KEY_ID}
      APP_STORE_CONNECT_ISSUER_ID:
        description: Apple Issuer ID (from env var)
        default: ${APP_STORE_CONNECT_ISSUER_ID}
      CM_EMAIL:
        description: Email to receive build notifications
        default: ${CM_EMAIL}

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js app and sync Capacitor iOS
        script: |
          npm install -g @capacitor/cli
          npm run build
          npx cap sync ios

      - name: Archive iOS app (xcodebuild)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/ios_archive" \
            clean archive

      - name: Export IPA
        script: |
          cat > "$CM_BUILD_DIR/ExportOptions.plist" << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ios_build" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" | xcpretty

    artifacts:
      - $CM_BUILD_DIR/ios_build/*.ipa
      - $CM_BUILD_DIR/ios_archive.xcarchive

    publishing:
      app_store_connect:
        # auth inferred from fields below; no 'auth:' line needed
        api_key: ${{ inputs.APP_STORE_CONNECT_PRIVATE_KEY }}
        key_id: ${{ inputs.APP_STORE_CONNECT_KEY_ID }}
        issuer_id: ${{ inputs.APP_STORE_CONNECT_ISSUER_ID }}
        submit_to_testflight: true

      email:
        recipients:
          - ${{ inputs.CM_EMAIL }}
