workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    # Pull secrets/vars from the "ios" group (set these in Codemagic → Environment variables)
    # Required in group "ios":
    #   APP_STORE_CONNECT_PRIVATE_KEY   (base64 of your .p8 contents)
    #   APP_STORE_CONNECT_KEY_ID
    #   APP_STORE_CONNECT_ISSUER_ID
    #   CM_EMAIL                        (where build results will be emailed)
    #   NEXT_PUBLIC_SUPABASE_URL
    #   NEXT_PUBLIC_SUPABASE_ANON_KEY
    environment:
      groups:
        - ios
      vars:
        NODE_VERSION: 20
        XCODE_VERSION: 15.0

    cache:
      cache_paths:
        - ~/.npm
        - $HOME/Library/Caches/CocoaPods
        - ios/**/Pods

    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm -v
          npm ci

      - name: Build Next.js app (static export) & sync Capacitor
        script: |
          npm install -g @capacitor/cli
          npm run build              # uses next.config.mjs to export to ./out
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Archive iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          # Minimal ExportOptions for App Store/TestFlight
          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          cd ios/App
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/ios_build" \
            -allowProvisioningUpdates

    artifacts:
      - $CM_BUILD_DIR/ios_build/*.ipa
      - $CM_BUILD_DIR/ios_archive.xcarchive

    publishing:
      # Upload to App Store Connect / TestFlight using API key
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

      # Email the build result
      email:
        recipients:
          - $CM_EMAIL
